DROP TABLE IF EXISTS carga CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS contato CASCADE;
DROP TABLE IF EXISTS estacao CASCADE;
DROP TABLE IF EXISTS funcionario CASCADE;
DROP TABLE IF EXISTS funcionarioviagem CASCADE;
DROP TABLE IF EXISTS locomotiva CASCADE;
DROP TABLE IF EXISTS log CASCADE;
DROP TABLE IF EXISTS manutencao CASCADE;
DROP TABLE IF EXISTS rota CASCADE;
DROP TABLE IF EXISTS tipofuncionario CASCADE;
DROP TABLE IF EXISTS tipovagao CASCADE;
DROP TABLE IF EXISTS vagao CASCADE;
DROP TABLE IF EXISTS viagem CASCADE;
DROP TABLE IF EXISTS viagemvagao CASCADE;

-- ============================================================================================================================
-- 2023/2
-- 08/11/2023

ALTER TABLE viagem DROP CONSTRAINT FKviagem768070;
ALTER TABLE viagemvagao DROP CONSTRAINT FKviagemvaga821457;
ALTER TABLE viagemvagao DROP CONSTRAINT FKviagemvaga429978;
ALTER TABLE rota DROP CONSTRAINT FKrota934183;
ALTER TABLE rota DROP CONSTRAINT FKrota579318;
ALTER TABLE funcionario DROP CONSTRAINT FKfuncionari560815;
ALTER TABLE funcionario DROP CONSTRAINT FKfuncionari680980;
ALTER TABLE funcionarioviagem DROP CONSTRAINT FKfuncionari853514;
ALTER TABLE funcionarioviagem DROP CONSTRAINT FKfuncionari444446;
ALTER TABLE vagao DROP CONSTRAINT FKvagao327069;
ALTER TABLE carga DROP CONSTRAINT FKcarga858886;
ALTER TABLE carga DROP CONSTRAINT FKcarga654615;
ALTER TABLE contato DROP CONSTRAINT FKcontato84069;
ALTER TABLE carga DROP CONSTRAINT FKcarga987407;
ALTER TABLE manutencao DROP CONSTRAINT FKmanutencao963723;
ALTER TABLE manutencao DROP CONSTRAINT FKmanutencao4100;
ALTER TABLE manutencao DROP CONSTRAINT FKmanutencao192529;
ALTER TABLE viagemrota DROP CONSTRAINT FKviagemrota253688;
ALTER TABLE viagemrota DROP CONSTRAINT FKviagemrota854197;
ALTER TABLE viagemvagao DROP CONSTRAINT FKviagemvaga445439;
DROP TABLE IF EXISTS carga CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS contato CASCADE;
DROP TABLE IF EXISTS estacao CASCADE;
DROP TABLE IF EXISTS funcionario CASCADE;
DROP TABLE IF EXISTS funcionarioviagem CASCADE;
DROP TABLE IF EXISTS locomotiva CASCADE;
DROP TABLE IF EXISTS log CASCADE;
DROP TABLE IF EXISTS manutencao CASCADE;
DROP TABLE IF EXISTS rota CASCADE;
DROP TABLE IF EXISTS tipofuncionario CASCADE;
DROP TABLE IF EXISTS tipovagao CASCADE;
DROP TABLE IF EXISTS vagao CASCADE;
DROP TABLE IF EXISTS viagem CASCADE;
DROP TABLE IF EXISTS viagemrota CASCADE;
DROP TABLE IF EXISTS viagemvagao CASCADE;
